index:
  path: /
  controller: App\Controller\DefaultController::index
logout:
  path: /logout
  controller: App\Controller\DefaultController::logout
introduction:
  path: /exercise/introduction/
  controller: App\Controller\IntroductionController::index
introduction/save:
  path: /exercise/introduction/save
  controller: App\Controller\IntroductionController::save
introduction/check:
  path: /exercise/introduction/check
  controller: App\Controller\IntroductionController::check
web:
  path: /exercise/web/
  controller: App\Controller\WebFlowController::index
web/authz:
  path: /exercise/web/authz
  controller: App\Controller\WebFlowController::authz
web/save:
  path: /exercise/web/save
  controller: App\Controller\WebFlowController::save
native:
  path: /exercise/native/
  controller: App\Controller\NativeFlowController::index
native/authz:
  path: /exercise/native/authz
  controller: App\Controller\NativeFlowController::authz
native/save:
  path: /exercise/native/save
  controller: App\Controller\NativeFlowController::save
spa:
  path: /exercise/spa/
  controller: App\Controller\SPAFlowController::index
spa/authz:
  path: /exercise/spa/authz
  controller: App\Controller\SPAFlowController::authz
spa/save:
  path: /exercise/spa/save
  controller: App\Controller\SPAFlowController::save
refresh:
  path: /exercise/refresh/
  controller: App\Controller\RefreshTokenController::index
refresh/authz:
  path: /exercise/refresh/authz
  controller: App\Controller\RefreshTokenController::authz
refresh/save:
  path: /exercise/refresh/save
  controller: App\Controller\RefreshTokenController::save
refresh/refresh:
  path: /exercise/refresh/refresh
  controller: App\Controller\RefreshTokenController::refresh
device:
  path: /exercise/device/
  controller: App\Controller\DeviceFlowController::index
service:
  path: /exercise/service/
  controller: App\Controller\ServiceFlowController::index
service/save:
  path: /exercise/service/save
  controller: App\Controller\ServiceFlowController::save
openid:
  path: /exercise/openid/
  controller: App\Controller\OpenIDFlowController::index
openid/authz:
  path: /exercise/openid/authz
  controller: App\Controller\OpenIDFlowController::authz
openid/save:
  path: /exercise/openid/save
  controller: App\Controller\OpenIDFlowController::save
openid/claims:
  path: /exercise/openid/claims
  controller: App\Controller\OpenIDFlowController::claims
api:
  path: /exercise/api/
  controller: App\Controller\APIController::index
revoke:
  path: /exercise/revoke/
  controller: App\Controller\RevokedController::index
scopes:
  path: /exercise/scopes/
  controller: App\Controller\ScopeController::index

challenge:
  path: /challenge/
  controller: App\Controller\ChallengeController::challenge

challenge/1:
  path: /challenge/1
  controller: App\Controller\ChallengeController::challenge1
challenge/1/start:
  path: /challenge/1/start
  controller: App\Controller\ChallengeController::challenge1start
challenge/1/save:
  path: /challenge/1/save
  controller: App\Controller\ChallengeController::challenge1save
challenge/1/claim:
  path: /challenge/1/claim
  controller: App\Controller\ChallengeController::challenge1claim
challenge/1/claimsave:
  path: /challenge/1/claimsave
  controller: App\Controller\ChallengeController::challenge1claimsave
challenge/1/reset:
  path: /challenge/1/reset
  controller: App\Controller\ChallengeController::challenge1reset

admin:
  path: /admin
  controller: App\Controller\AdminController:index
admin/login:
  path: /admin/login
  controller: App\Controller\AdminController:login_start
admin/login/callback:
  path: /admin/callback
  controller: App\Controller\AdminController:login_callback




